/* export const GET_USER_VOICE_TEXT = 'GET_USER_VOICE_TEXT';
export const GET_NEAREST_BUSINESS = 'GET_NEAREST_BUSINESS';
export const LOADING_NEAREST_BUSINESS = 'LOADING_NEAREST_BUSINESS';
export const GETTING_NEAREST_BUSINESS_FAILED = 'GETTING_NEAREST_BUSINESS_FAILED'; */